In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
#price =m1*area+m2*bedroom+m3*hall+b
df=pd.read_csv(r"C:\Users\meetm\Desktop\Machine_learning concept\linear regression with multiple variable\linear regression with multiple variable.csv")

In [3]:
df
#here a is area  

bedroom  age     a   price
0      3.0   20  2600  550000
1      4.0   15  3000  565000
2      NaN   18  3200  610000
3      3.0   30  3600  595000
4      5.0    8  4000  760000

In [4]:
import math
#math.floor convert floating point to integer
median_bedroom =math.floor(df.bedroom.median())
median_bedroom

3

In [5]:
df.bedroom=df.bedroom.fillna(median_bedroom)
#fillna fill all null values in bedroom columns with median_bedroom

In [6]:
df

bedroom  age     a   price
0      3.0   20  2600  550000
1      4.0   15  3000  565000
2      3.0   18  3200  610000
3      3.0   30  3600  595000
4      5.0    8  4000  760000

In [7]:
reg=linear_model.LinearRegression()

In [8]:
reg.fit(df[['a','bedroom','age']],df.price)

LinearRegression()

In [9]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
reg.intercept_

383724.9999999998

In [11]:
reg.predict([[3000,3,12]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([635500.])

In [12]:
#practice with given data set of hiring


In [13]:
d=pd.read_csv(r"C:\Users\meetm\Desktop\Machine_learning concept\linear regression with multiple variable\hiring.csv")

In [14]:
d

experience  test score out of 10  interview score ()  salary
0        NaN                   8.0                   9   50000
1        NaN                   8.0                   6   45000
2       five                   6.0                   7   60000
3       two                   10.0                  10   65000
4      seven                   9.0                   6   70000
5      three                   7.0                  10   62000
6        ten                   NaN                   7   72000
7     eleven                   7.0                   8   80000

In [15]:
d.experience=d.experience.fillna('zero')
d


experience  test score out of 10  interview score ()  salary
0       zero                   8.0                   9   50000
1       zero                   8.0                   6   45000
2       five                   6.0                   7   60000
3       two                   10.0                  10   65000
4      seven                   9.0                   6   70000
5      three                   7.0                  10   62000
6        ten                   NaN                   7   72000
7     eleven                   7.0                   8   80000

In [16]:
!pip install word2number
from word2number import w2n


Defaulting to user installation because normal site-packages is not writeable


In [17]:
d.experience = d.experience.apply(w2n.word_to_num)

In [18]:
d

experience  test score out of 10  interview score ()  salary
0           0                   8.0                   9   50000
1           0                   8.0                   6   45000
2           5                   6.0                   7   60000
3           2                  10.0                  10   65000
4           7                   9.0                   6   70000
5           3                   7.0                  10   62000
6          10                   NaN                   7   72000
7          11                   7.0                   8   80000

In [19]:
import math
mean_test_score = math.floor(d['test score out of 10'].mean())
mean_test_score

7

In [20]:
d['test score out of 10'] = d['test score out of 10'].fillna(mean_test_score)
d

experience  test score out of 10  interview score ()  salary
0           0                   8.0                   9   50000
1           0                   8.0                   6   45000
2           5                   6.0                   7   60000
3           2                  10.0                  10   65000
4           7                   9.0                   6   70000
5           3                   7.0                  10   62000
6          10                   7.0                   7   72000
7          11                   7.0                   8   80000

In [21]:
reg = linear_model.LinearRegression()
reg.fit(d[['experience','test score out of 10','interview score ()']],d['salary'])

LinearRegression()

In [22]:
reg.predict([[2,9,6]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [23]:
reg.predict([[12,10,10]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])