In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt


In [4]:
from sklearn import linear_model

In [6]:
df =pd.read_csv("C:/Users/meetm/Desktop/Machine_learning concept/linear regression with single varible/linear regretion with one variable.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
rg = linear_model.LinearRegression()

In [8]:
rg.fit(df[['area']],df.price) #training data to model

LinearRegression()

In [9]:
rg.coef_

array([135.78767123])

In [10]:
rg.intercept_

180616.43835616432

In [11]:
rg.predict([[3300]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In [12]:
import pickle 

In [14]:
with open('model_pickle','wb') as f:
    pickle.dump(rg,f)
    #save model into file

In [16]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)
    #loaded from a file to memory

In [17]:
mp.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [23]:
# if you have lot of numpy array than joblib is more efficient
#from sklearn.externals import joblib
import joblib


In [25]:
joblib.dump(mp,'model_joblib')

['model_joblib']

In [26]:
mj=joblib.load('model_joblib')

In [27]:
mj.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])